-- Add migration script here
create table if not exists templates
(
    id          bigint generated by default as identity,
    name        varchar     not null default '' unique,
    description varchar     not null default '',
    body        varchar     not null default '',
    created_at  timestamptz not null default current_timestamp,
    updated_at  timestamptz not null default current_timestamp
);

alter table templates
    add constraint templates_id_pk primary key (id);

create table if not exists inputs
(
    id            bigint generated by default as identity,
    name          varchar     not null default '',
    default_value varchar     not null default '',
    template_id   bigint      not null references templates (id) on delete cascade
);

alter table inputs
    add constraint inputs_id_pk primary key (id);
